webtalk_init -webtalk_dir C:\\ECE532\\NexysVideo-master3\\NexysVideo-master\\Projects\\hdmi\\proj\\hdmi.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Feb 28 20:27:45 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "fc54mjvuqupdl89skus2b5nvej" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2016.2_8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1488235245508" -context "sdk\\\\bsp/1488235245508"
webtalk_add_data -client sdk -key hwid -value "1488134110962" -context "sdk\\\\bsp/1488235245508"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1488235245508"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1488235245508"
webtalk_add_data -client sdk -key uid -value "1488235262748" -context "sdk\\\\application/1488235262748"
webtalk_add_data -client sdk -key hwid -value "1488134110962" -context "sdk\\\\application/1488235262748"
webtalk_add_data -client sdk -key bspid -value "1488235245508" -context "sdk\\\\application/1488235262748"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1488235262748"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1488235262748"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1488235262748"
webtalk_add_data -client sdk -key uid -value "1488236088916" -context "sdk\\\\bsp/1488236088916"
webtalk_add_data -client sdk -key hwid -value "1488134110962" -context "sdk\\\\bsp/1488236088916"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1488236088916"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1488236088916"
webtalk_add_data -client sdk -key uid -value "1488236136173" -context "sdk\\\\application/1488236136173"
webtalk_add_data -client sdk -key hwid -value "1488134110962" -context "sdk\\\\application/1488236136173"
webtalk_add_data -client sdk -key bspid -value "1488236088916" -context "sdk\\\\application/1488236136173"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1488236136173"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1488236136173"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1488236136173"
webtalk_transmit -clientid 2204528636 -regid "" -xml C:\\ECE532\\NexysVideo-master3\\NexysVideo-master\\Projects\\hdmi\\proj\\hdmi.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\ECE532\\NexysVideo-master3\\NexysVideo-master\\Projects\\hdmi\\proj\\hdmi.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\ECE532\\NexysVideo-master3\\NexysVideo-master\\Projects\\hdmi\\proj\\hdmi.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
